@extends('layouts.thrive')
@section('title', 'Alerts | THRIVE')
@section('content')
<div class="mb-4"><p class="eyebrow mb-1">EARLY WARNING / EARLY ACTION</p><h1 class="h2 mb-1">Active alerts</h1><p class="text-muted mb-0">Turn an evidence-linked signal into a recorded response.</p></div>
<div id="alert-list" class="row g-3"><div class="col-12 text-muted">Loading alerts...</div></div>
@endsection
@section('scripts')
<script>
const csrf=document.querySelector('meta[name="csrf-token"]').content;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const statusLabel=status=>({pending:'Not started',acknowledged:'Acknowledged',in_progress:'In progress',completed:'Completed'}[status]||'Not started');
function actionForm(alert){const action=alert.action||{};const status=action.status||'pending';if(status==='completed')return `<div class="alert alert-success py-2 small mb-0"><strong>Action completed</strong>${action.actor_name?` by ${esc(action.actor_name)}`:''}${action.notes?`<br>${esc(action.notes)}`:''}</div>`;return `<form class="action-form border-top pt-3 mt-3" data-alert="${alert.id}"><div class="row g-2"><div class="col-md-5"><label class="form-label small mb-1">Responder name</label><input name="actor_name" class="form-control form-control-sm" required value="${esc(action.actor_name||'')}"></div><div class="col-md-7"><label class="form-label small mb-1">Response status</label><select name="status" class="form-select form-select-sm"><option value="acknowledged" ${status==='acknowledged'?'selected':''}>Acknowledge</option><option value="in_progress" ${status==='in_progress'?'selected':''}>Start action</option><option value="completed">Mark completed</option></select></div><div class="col-12"><label class="form-label small mb-1">Notes (facility-level only)</label><textarea name="notes" class="form-control form-control-sm" rows="2" placeholder="Record the aggregate response, not personal health details.">${esc(action.notes||'')}</textarea></div><div class="col-12"><button class="btn btn-sm btn-primary" type="submit">Save response</button><span class="small text-muted ms-2 form-status"></span></div></div></form>`}
function render(alerts){const list=document.getElementById('alert-list');if(!alerts.length){list.innerHTML='<div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body"><strong>No active alerts</strong><p class="small text-muted mb-0 mt-1">The alert engine has not identified an available warning signal.</p></div></div></div>';return}list.innerHTML=alerts.map(a=>`<div class="col-12 col-lg-6"><article class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex justify-content-between gap-3 mb-2"><span class="badge text-bg-${a.severity==='red'?'danger':'warning'}">${esc(a.severity.toUpperCase())}</span><small class="text-muted">${esc(a.hazard)}</small></div><h2 class="h5">${esc(a.title)}</h2><p class="text-muted">${esc(a.summary)}</p><div class="small bg-light rounded p-2 mb-3"><strong>Who should act:</strong> ${esc(a.metadata?.audience||'Local response team')}<br><strong>Action window:</strong> ${esc(a.metadata?.action_window||'Review now')}<br><strong>Current status:</strong> ${esc(statusLabel(a.action?.status))}</div><h3 class="h6">Recommended actions</h3><ul class="small mb-3">${(a.recommended_actions||[]).map(action=>`<li>${esc(action)}</li>`).join('')}</ul><small class="text-muted">Source: ${esc(a.source)} · Confidence: ${esc(a.metadata?.confidence||'not stated')}</small>${actionForm(a)}</div></article></div>`).join('');document.querySelectorAll('.action-form').forEach(form=>form.addEventListener('submit',saveAction))}
async function saveAction(event){event.preventDefault();const form=event.currentTarget,status=form.querySelector('.form-status'),body=Object.fromEntries(new FormData(form));status.textContent='Saving...';try{const response=await fetch(`/api/alerts/${form.dataset.alert}/action`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify(body)});if(!response.ok)throw new Error('Unable to save');await loadAlerts()}catch(error){status.textContent='Could not save response.'}}
async function loadAlerts(){const response=await fetch('{{ route('climate.alerts') }}');const data=await response.json();render(data.alerts||[])}
loadAlerts().catch(()=>document.getElementById('alert-list').innerHTML='<div class="col-12 text-danger">Alert data is temporarily unavailable.</div>');
</script>
@endsection
