@extends('layouts.thrive')
@section('title', 'Data Health | THRIVE')
@section('content')
<div class="mb-4"><p class="eyebrow mb-1">TRUST AND PROVENANCE</p><h1 class="h2 mb-1">Data health</h1><p class="text-muted mb-0">Know what is live, queued, complete, or awaiting authorization.</p></div>
<div id="pipeline-grid" class="row g-3"><div class="col-12 text-muted">Loading pipeline status...</div></div>
<section class="card border-0 shadow-sm mt-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-3"><div><p class="eyebrow mb-1">HEALTH & ACTIVITIES ENGINE</p><h2 class="h5 mb-1">Decision-support coverage</h2><p class="small text-muted mb-0">These modules translate environmental signals into practical guidance for children, communities and health services.</p></div><span id="health-linkage-status" class="badge text-bg-secondary">Checking outcome linkage...</span></div><div id="activity-readiness" class="row g-3"><div class="col-12 text-muted">Loading health and activity modules...</div></div><div id="health-inputs" class="small text-muted border-top mt-3 pt-3">Checking signal inputs...</div></div></section>
<section class="card border-0 shadow-sm mt-4"><div class="card-body"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3"><div><p class="eyebrow mb-1">DHIS2 HEALTH FEED</p><h2 class="h5 mb-1">Aggregate outcome synchronisation</h2><p id="dhis2-status" class="small text-muted mb-0">Checking connector configuration...</p></div><div class="d-flex gap-2"><input id="dhis2-period" class="form-control" type="month" style="width:auto"><button id="dhis2-sync" class="btn btn-outline-success">Sync DHIS2</button></div></div><div id="dhis2-message" class="small mt-3" aria-live="polite"></div></div></section>
<section class="card border-0 shadow-sm mt-4"><div class="card-body"><div class="mb-3"><p class="eyebrow mb-1">PEST OUTLOOK ENGINE</p><h2 class="h5 mb-1">Pest-risk module coverage</h2><p class="small text-muted mb-0">Prevention-focused environmental screening for mosquito, indoor-pest and outdoor-pest activity.</p></div><div id="pest-readiness" class="row g-3"><div class="col-12 text-muted">Loading pest modules...</div></div></div></section>
@endsection
@section('scripts')
<script>
Promise.all([fetch('{{ route('climate.pipeline-status') }}').then(r => r.json()), fetch('{{ route('climate.district-risk') }}').then(r => r.json()), fetch('{{ route('climate.air-quality-risk') }}').then(r => r.json()), fetch('{{ route('climate.pilot-report') }}?days=30').then(r => r.json()), fetch('{{ route('climate.dhis2-status') }}').then(r => r.json())]).then(([p, f, a, report, dhis]) => {
    const c = p.chirps || {}, h = p.facility_registry || {};
    const cards = [['District boundaries', p.districts, 'Synchronized'], ['Facilities', h.total || 0, `${h.verified || 0} verified · ${h.candidate || 0} candidate`], ['CHIRPS queued', c.queued || 0, 'Awaiting worker'], ['CHIRPS complete', c.complete || 0, 'Processed'], ['OpenAQ connector', p.openaq === 'configured' ? 'Configured' : 'Not configured', 'API key status'], ['Flood risk scores', f.available ? 'Available' : 'Awaiting baselines', 'District anomalies'], ['Air anomalies', a.available ? 'Available' : 'Awaiting history', 'Seven-observation baseline'], ['DHIS2 health feed', dhis.configured ? 'Configured' : 'Awaiting setup', `${dhis.indicators_configured || 0} indicators · ${dhis.org_units_configured || 0} org units`]];
    document.getElementById('pipeline-grid').innerHTML = cards.map(x => `<div class="col-12 col-md-6 col-xl-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><small class="text-muted">${x[0]}</small><div class="h3 mb-1">${x[1]}</div><p class="small text-muted mb-0">${x[2]}</p></div></div></div>`).join('');
    const activities = [
        ['School play & learning', 'Heat, AQI and UV', 'Children', 'success'],
        ['Community movement', 'Rainfall and wind', 'Access and referrals', 'success'],
        ['Outdoor field work', 'Heat, rain and wind', 'Field teams', 'success'],
        ['Sensitive health', 'AQI and PM2.5', 'Respiratory-sensitive children', 'success']
    ];
    document.getElementById('activity-readiness').innerHTML = activities.map(x => `<div class="col-12 col-md-6 col-xl-3"><div class="border rounded-3 p-3 h-100"><div class="d-flex justify-content-between gap-2"><strong class="small">${x[0]}</strong><span class="badge text-bg-${x[3]}">Ready</span></div><div class="small text-muted mt-2">Inputs: ${x[1]}</div><div class="small text-muted">Audience: ${x[2]}</div></div></div>`).join('');
    const health = report.health_outcomes || {};
    const linkage = document.getElementById('health-linkage-status');
    linkage.className = `badge text-bg-${health.status === 'connected' ? 'success' : 'warning'}`;
    linkage.textContent = health.status === 'connected' ? `Outcome linkage connected · ${health.records} records` : 'Outcome linkage awaiting data';
    document.getElementById('health-inputs').innerHTML = `Active decision inputs: weather forecast · heat stress · rainfall/flood exposure · air quality · UV index. Current outcome indicators: ${(health.indicators || []).join(', ') || 'none connected yet'}.`;
    const pests = [['Mosquitos', 'Warmth · humidity · rain', 'Standing-water prevention'], ['Indoor Pests', 'Humidity · warmth · rain', 'Ventilation and sanitation'], ['Outdoor Pests', 'Warmth · humidity · rain', 'Protective field planning']];
    document.getElementById('pest-readiness').innerHTML = pests.map(x => `<div class="col-12 col-md-4"><div class="border rounded-3 p-3 h-100"><div class="d-flex justify-content-between gap-2"><strong class="small">${x[0]}</strong><span class="badge text-bg-success">Ready</span></div><div class="small text-muted mt-2">Inputs: ${x[1]}</div><div class="small text-muted">Use: ${x[2]}</div></div></div>`).join('');
    const latest = dhis.latest_sync;
    document.getElementById('dhis2-status').textContent = dhis.configured ? `Configured · ${latest ? `last sync ${latest.status}, ${latest.records_ingested} records` : 'no sync has been run yet'}` : 'Connector disabled. Add DHIS2 settings to .env before syncing.';
}).catch(() => document.getElementById('pipeline-grid').innerHTML = '<div class="col-12 text-danger">Pipeline status is temporarily unavailable.</div>');
document.getElementById('dhis2-period').value = new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString().slice(0, 7);
document.getElementById('dhis2-sync').addEventListener('click', async () => { const message = document.getElementById('dhis2-message'); message.className = 'small mt-3 text-muted'; message.textContent = 'Starting DHIS2 sync...'; try { const response = await fetch('{{ route('climate.dhis2-sync') }}', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content }, body: JSON.stringify({ period: document.getElementById('dhis2-period').value }) }); const result = await response.json(); message.className = `small mt-3 ${result.status === 'complete' ? 'text-success' : 'text-warning'}`; message.textContent = result.error || `${result.status}: ${result.records_ingested || 0} records processed.`; } catch (error) { message.className = 'small mt-3 text-danger'; message.textContent = 'DHIS2 sync is temporarily unavailable.'; } });
</script>
@endsection
