@extends('layouts.thrive')
@section('title', 'Point-of-Care Support | THRIVE')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
    <div><p class="eyebrow mb-1">POINT-OF-CARE SUPPORT</p><h1 class="h2 mb-1">Continuity toolkit</h1><p class="text-muted mb-0">Offline-ready actions for frontline teams during climate hazards.</p></div>
    <label class="small text-muted">Language <select id="language" class="form-select form-select-sm mt-1"><option value="en">English</option><option value="sw">Kiswahili</option></select></label>
</div>
<div class="alert alert-info border-0 shadow-sm"><strong data-i18n="privacyTitle">Privacy by design</strong><div class="small" data-i18n="privacyText">Record only facility-level completion. Do not enter names, child records, diagnoses, or identifiable case details here.</div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><div><p class="eyebrow mb-1">LIVE CONTEXT</p><h2 class="h5 mb-0">Current hazard signals</h2></div><span id="signal-status" class="badge text-bg-secondary">Loading</span></div><div id="signals" class="row g-2 mt-2"><div class="col-12 small text-muted">Checking active alerts...</div></div></div></div>
<div class="row g-3">
    <div class="col-12 col-lg-7"><div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center"><div><p class="eyebrow mb-1">ACTION CHECKLIST</p><h2 class="h5" data-i18n="checklistTitle">Prepare the service</h2></div><button id="reset" class="btn btn-sm btn-outline-secondary" data-i18n="reset">Reset</button></div><div id="checklist" class="vstack gap-2 mt-3"></div></div></div></div>
    <div class="col-12 col-lg-5"><div class="card border-0 shadow-sm mb-3"><div class="card-body"><p class="eyebrow mb-1">ESCALATION</p><h2 class="h5" data-i18n="escalationTitle">When to escalate</h2><ul class="small mb-0"><li data-i18n="escalation1">Activate the facility continuity lead when essential services may stop.</li><li data-i18n="escalation2">Notify the district health team when access, power, water, or medicines are threatened.</li><li data-i18n="escalation3">Use local emergency channels for immediate danger; this tool is not an emergency dispatch service.</li></ul></div></div><div class="card border-0 shadow-sm"><div class="card-body"><p class="eyebrow mb-1">LOCAL STATUS</p><h2 class="h5" id="sync-status">Ready offline</h2><p class="small text-muted mb-0">Checklist progress is stored only on this device.</p></div></div></div>
</div>
@endsection
@section('scripts')
<script>
const copy={en:{privacyTitle:'Privacy by design',privacyText:'Record only facility-level completion. Do not enter names, child records, diagnoses, or identifiable case details here.',checklistTitle:'Prepare the service',reset:'Reset',escalationTitle:'When to escalate',escalation1:'Activate the facility continuity lead when essential services may stop.',escalation2:'Notify the district health team when access, power, water, or medicines are threatened.',escalation3:'Use local emergency channels for immediate danger; this tool is not an emergency dispatch service.'},sw:{privacyTitle:'Faragha kwa muundo',privacyText:'Rekodi hali ya kituo pekee. Usiingize majina, kumbukumbu za watoto, utambuzi, au taarifa za kumtambulisha mtu.',checklistTitle:'Andaa huduma',reset:'Anza upya',escalationTitle:'Wakati wa kutoa taarifa',escalation1:'Washa kiongozi wa mwendelezo wa huduma wakati huduma muhimu zinaweza kusimama.',escalation2:'Iarifu timu ya afya ya wilaya wakati usafiri, umeme, maji, au dawa ziko hatarini.',escalation3:'Tumia njia za dharura za eneo lako kwa hatari ya papo hapo; zana hii si huduma ya kutuma msaada.'}};
const tasks=[['hazard','Confirm the current hazard and facility alert level.'],['people','Check staff availability, safe access, and referral contacts.'],['supplies','Check essential medicines, water, power, cold chain, and communications.'],['children','Prioritize continuity for child health, immunization, nutrition, and safeguarding services.'],['report','Share only an aggregate facility status with the district response team.']];
const key='thrive-support-checklist'; let done=JSON.parse(localStorage.getItem(key)||'{}');
function render(){document.getElementById('checklist').innerHTML=tasks.map(([id,label])=>`<label class="d-flex gap-2 align-items-start border rounded p-3"><input class="form-check-input mt-1" type="checkbox" data-id="${id}" ${done[id]?'checked':''}><span>${label}</span></label>`).join('');document.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>{done[x.dataset.id]=x.checked;localStorage.setItem(key,JSON.stringify(done));});}
function translate(lang){document.querySelectorAll('[data-i18n]').forEach(x=>x.textContent=copy[lang][x.dataset.i18n]);}
document.getElementById('language').onchange=e=>translate(e.target.value);document.getElementById('reset').onclick=()=>{done={};localStorage.removeItem(key);render()};render();
fetch('{{ route('climate.alerts') }}').then(r=>r.json()).then(data=>{const alerts=data.alerts||[],status=document.getElementById('signal-status'),target=document.getElementById('signals');status.textContent=alerts.length?`${alerts.length} active`:'No active alerts';status.className=`badge text-bg-${alerts.some(a=>a.severity==='red')?'danger':alerts.length?'warning':'success'}`;target.innerHTML=alerts.length?alerts.slice(0,4).map(a=>`<div class="col-12 col-md-6"><div class="border rounded p-2 small"><strong>${a.title}</strong><div class="text-muted">${a.severity.toUpperCase()} · ${a.source||'THRIVE screening'}</div></div></div>`).join(''):'<div class="col-12 small text-muted">No active system alerts. Continue routine preparedness checks.</div>'}).catch(()=>{document.getElementById('signal-status').textContent='Offline';document.getElementById('signals').innerHTML='<div class="col-12 small text-muted">Live signals unavailable. Use the checklist and follow local response protocols.</div>'});
</script>
@endsection
